### ISSUE TITLE
company-dcd-show-ddoc-with-buffer does not work on 1st character of a symbol

### ISSUE THREAD

**Issue by tuhdo** [tsukimizake/company-dcd#10]
How to reproduce:
- Place the cursor on first character of any symbol.
- Run `company-dcd-show-ddoc-with-buffer`.
- Got empty buffer.

However, when the cursor is at 2nd character or higher, it works. `(company-dcd--cursor-position)` returns off-by-one position compared with `(point)`. 

I'm not sure why the code must subtract by 1 here:

``` lisp
(defsubst company-dcd--cursor-position ()
  "Get the current cursor position to pass to dcd-client."
  (1- (position-bytes (point))))
```

**Comment by CyberShadow** [comment]
> I'm not sure why the code must subtract by 1 here:

The decrement is needed for accurate completion results. Perhaps DCD is inconsistent in how it counts coordinates.

**Comment by tuhdo** [comment]
Hmm then maybe it's better another cursor function for `company-dcd-show-ddoc-with-buffer` that does not subtract?
