### ISSUE TITLE
Takes too long to open an existing d-file

### ISSUE THREAD

**Issue by ghost** [tsukimizake/company-dcd#12]
Hi!
I'm using company-dcd and it's very useful, but whenever I open an existing d-file in my project it takes a very loooong time until the file is ready in emacs to be edited.
I've checked what makes this operation so slow and it seems to be the call to 'dub describe' that is done with every file opened (I use dub for my projects).
Is it possible to reduce this opening time?
Thanks for your work on company-dcd!

**Comment by tsukimizake** [comment]
Hi. Thank you for detail report.
I tried to implement a cache in order not to call dub every time.

But I don't have a large dub project, so I wonder if it works correct. Please let me know after updating your package. 

Thanks.

**Comment by ghost** [comment]
Hi tsukimizake!
Thanks for your quick response!
I've just tried it :)
Way, way quicker!!!

**Comment by tsukimizake** [comment]
Great!
