### ISSUE TITLE
No hard dependency on ivy

### ISSUE THREAD

**Issue by arichiardi** [tsukimizake/company-dcd#15]
Hi there!

I am fiddling with this package and unfortunately I don't use `ivy` (but `helm`).

I was wondering whether you were interested in a version where `ivy` is not a hard dependency so that folks don't have to install it just for using this package.

I can contribute a version but I thought I should ask first :smile: 

Thank you for this package!

**Comment by arichiardi** [comment]
Trying to found what would be the best way I found [this reddit post](https://www.reddit.com/r/emacs/comments/4dlk68/what_is_best_way_to_create_optional_library/)

and:

> I think conditional dependencies should be considered an anti-pattern. If you have core functionality that doesn't depend on helm, then publish that. If you have optional functionality that does depend on helm, publish it separately. 

Something to consider as well. Looking forward to your answer.

**Comment by CyberShadow** [comment]
Hi,

None of the functionality in the package actually requires ivy-mode, except commands which explicitly invoke ivy-mode at the user's explicit request.

Removing the dependency entry and wrapping the affected code in a `eval-after-load` or `(when (require 'ivy-mode nil t) ...)` seems like an appropriate change.
