### ISSUE TITLE
no auto complete suggestions at all and there is no warnings/erros.

### ISSUE THREAD

**Issue by timepp** [tsukimizake/company-dcd#2]
Hi I setup company-dcd according to the instructions, then open a d source file, I see the dcd-server is launched. but there is no suggestions. 

I tried dcd-client with localtion and source file name, it can print the candidates successfully to console window. 

How can I do next to locate the problem?

**Comment by tsukimizake** [comment]
Thanks for feedback!
Can you tell me the result of these two checks?
- Can't you complete a function which is defined by yourself either?

``` D
void func(){

}

void main(){
  // pipe is cursor. Please call "M-x company-dcd" here.
  f|  
}
```

Does it work?
If it works, it would be an import problem.
- Else, does `M-: (company-dcd--get-candidates)` work?

First, insert following on D-mode buffer.

``` D
// pipe is cursor.
import std.|
```

And, tell `M-: (company-dcd--get-candidates)` to your Emacs.
It should show
`(#("zlib" 0 4 (company-dcd--help "M")) #("zip" 0 3 (company-dcd--help "M")) #("xml" 0 3 (company-dcd--help "M")) #("windows" 0 7 (company-dcd--help "P")) #("variant" 0 7 (company-dcd--help "M")) #("uuid" 0 4 (company-dcd--help "M")) #("utf" 0 3 (company-dcd--help "M")) #("uri" 0 3 (company-dcd--help "M")) #("uni" 0 3 (company-dcd--help "M")) #("typetuple" 0 9 (company-dcd--help "M")) #("typelist" 0 8 (company-dcd--help "M")) #("typecons" 0 8 (company-dcd--help "M")) ...)` 
or something like this on your minibuffer. 
If it doesn't work, the problem would be quite curious.

Regards,
tsukimizake

**Comment by tsukimizake** [comment]
Well, are you okay? 
Is it working now?

**Comment by timepp** [comment]
Hi tsukimizake,  
    I just see your message. I will try it later and post the result here. thanks.

**Comment by timepp** [comment]
Hi tsukimizake (つきみざけ, maybe :)):

just come back after a long period busy work. the problem disappears! sorry for the false negative.

thanks!!
