### ISSUE TITLE
Lack of parameter '-p 9166' in some places when calling dcd-client

### ISSUE THREAD

**Issue by antoniocorbi** [tsukimizake/company-dcd#3]
Hi tsukimizake!

When opening my D files with company-dcd enabled I get this error:
"std.socket.SocketOSException@/build/ldc/src/ldc/runtime/phobos/std/socket.d(2814): Unable to connect socket: No such file or directory"

I've nailed it down to a point where dcd-client is being called without the '-p 9166' parameter, but my lack of knowledge of emacs-lisp do not let me see where is it happenning.

So, for the time being, I've created a local 'dcd-client' script that always calls the real dcd-client supplying the '-p 9166' and company-dcd works.

Thanks for your work in company-dcd! it's great!
Antonio Corbi

**Comment by tsukimizake** [comment]
Thanks for the issue!

What does `M-: (company-dcd--build-args (company-dcd--cursor-position))` say? This function creates options for dcd-client.
It should show `("-c" "{cursor position}" "-p" "9166")` or something like this.

Regards,
tsukimizake

**Comment by antoniocorbi** [comment]
Hi again  tsukimizake,

Yes, it says something like you say it should say, it's weird because if I remove my local script faking the real dcd-client I get error messages like this:

Sat Mar 19 18:51:07 2016
"dcd-client -I/usr/include/dlang/dmd -I/home/acorbi/Documentos/Tesis/dgtaligner/src/ -I/home/acorbi/Documentos/Tesis/dgtaligner/src -I/home/acorbi/.dub/packages/gtk-d-3.2.3/src -I/home/acorbi/Documentos/Tesis/dgtaligner/src" failed.
Error type is: Unable to connect socket : No such file or directory

My local script is as simple as this one:
#! /bin/sh
/usr/bin/dcd-client -p 9166 $@

Thank's for your interest and help!
Antonio

**Comment by tsukimizake** [comment]
Maybe it's fixed now. Update via package manager will solve the problem.

I'm away from Dlang these days, so I may miss the changes or new functionalities of DCD.
If you find something again, please feel free to create issue.

Thanks again for the issue. Please close it if it works.
Have a nice holiday!

Regards,
tsukimizake

**Comment by antoniocorbi** [comment]
Hi again tsukimizake :)
Just updated from package manager, and it seems to work for me now!
_Wow!, that was fast!_

I'll let you know if find some more issues with company-dcd

Thank's for providing us with such a tool!
Antonio
