### ISSUE TITLE
Fail to load company-dcd

### ISSUE THREAD

**Issue by brdjns-zz** [tsukimizake/company-dcd#6]
company-dcd fails to initialise at startup with error `(void-function define-helm-type-attribute)`. The offending init line `(require 'company-dcd)` was then removed and replaced with an `autoload` expression. 

While this allows Emacs to initialise properly, company-dcd fails to load when visiting a file with a .d extension because of the same problem, now manifesting as a file mode specification error `(void-function define-helm-type-attribute)` in the minibuffer.

**Comment by tsukimizake** [comment]
Thanks for report.
It's coming from helm's destructive change. Temporary patched by disabling search-symbol now.

If it continues to fail after update, please reopen this issue.
Thanks!
