### ISSUE TITLE
company-dcd-helm-file-type broken

### ISSUE THREAD

**Issue by CyberShadow** [tsukimizake/company-dcd#7]
`company-dcd-helm-file-type` can no longer load because [Helm removed the helm-plugin module entirely](https://github.com/emacs-helm/helm/commit/cf106ec36f163743ab79cb6661442c4d8113a11d).

Removing the line `(require 'company-dcd-helm-file-type)` from `company-dcd.el` seems to get things going again, but I'm not sure what this breaks or how to reimlement the code without `helm-plugins`.

**Comment by tsukimizake** [comment]
I'm thinking about moving to ido or ivy. Helm is too active to go along.

**Comment by tsukimizake** [comment]
Ivy version is done. How do you think about it?
https://github.com/tsukimizake/company-dcd/tree/ivy-version

**Comment by CyberShadow** [comment]
I don't use the symbol search feature, but I tested that branch now and it seems to work :)

**Comment by tsukimizake** [comment]
Good. Thanks for the issue and check!
